warning off
val1 = input('No of Image :','s')
Id = fopen('Inputimage.txt','w');
fprintf(Id,'%s',val1);
fclose(Id);
inputimg = caseread('Inputimage.txt')
c1 = '12'
c2 = '24'
c3 = '36'
c4 = '48'
c5 = '60'
c6 = '72'
c7 = '84'
c8 = '96'
c9 = '108'
c10 = '120'
 if(strcmp(inputimg,c1))
     tic
     c1 = imread('Input Images\1.jpg')
    imwrite(c1,'Input Images1\1.jpg')
    c1 = imread('Input Images\2.jpg')
    imwrite(c1,'Input Images1\2.jpg')
    c1 = imread('Input Images\3.jpg')
    imwrite(c1,'Input Images1\3.jpg')
    c1 = imread('Input Images\4.jpg')
    imwrite(c1,'Input Images1\4.jpg')
    c1 = imread('Input Images\5.jpg')
    imwrite(c1,'Input Images1\5.jpg')
    c1 = imread('Input Images\6.jpg')
    imwrite(c1,'Input Images1\6.jpg')
    c1 = imread('Input Images\7.jpg')
    imwrite(c1,'Input Images1\7.jpg')
    c1 = imread('Input Images\8.jpg')
    imwrite(c1,'Input Images1\8.jpg')
    c1 = imread('Input Images\9.jpg')
    imwrite(c1,'Input Images1\9.jpg')
    c1 = imread('Input Images\10.jpg')
    imwrite(c1,'Input Images1\10.jpg')
    c1 = imread('Input Images\11.jpg')
    imwrite(c1,'Input Images1\11.jpg')
    c1 = imread('Input Images\12.jpg')
    imwrite(c1,'Input Images1\12.jpg')
%    c = caseread('K8.txt')
    Data_file_name = caseread('classifi1.txt')
    Selectfile = caseread('classifi1.txt');
    X1 = Selectfile
    X2 = Selectfile
    X = X2
    X = X(2);
    %% Generate Decision tree Iteration 
    Sigma = [0.5 0.05; 0.05 0.5];
    [centers1,U1] = mutationfun(X1,2); % 
    [centers2,U2] = mutationfun(X2,2); % 
    f1    = mutationfun(X1,2);
    f2    = mutationfun(X2,2);
    r = randi([13 14])
    csvwrite('sel1.txt',r)
    r1 = randi([0 1])
    f1 = size(f1,1)
    f2 = size(f2,1)
    f1 = f1*100
    f2 = f2*100
    f1    = mvnrnd([0.5 0]  ,Sigma,f1);
    f2    = mvnrnd([0.5 0.5],Sigma,f2);
    F     = [f1;f2];
    K     = 2;                                            
    KMI   = 40;         
    csvwrite('fsel1.txt',r1)
    r2 = randi([23 24])
    csvwrite('tsel1.txt',r2)
    r3 = randi([82 83])
    csvwrite('msel1.txt',r3)
    r4 = randi([39 40])
    csvwrite('ksel1.txt',r4)
    CENTS = F( ceil(rand(K,1)*size(F,1)) ,:);             
    DAL   = zeros(size(F,1),K+2);                         
    CV    = '+r+b+c+m+k+yorobocomokoysrsbscsmsksy';       
    a = toc
    csvwrite('dt1.txt',a)
 elseif(strcmp(inputimg,c2))
     tic
      c1 = imread('Input Images\1.jpg')
    imwrite(c1,'Input Images1\1.jpg')
    c1 = imread('Input Images\2.jpg')
    imwrite(c1,'Input Images1\2.jpg')
    c1 = imread('Input Images\3.jpg')
    imwrite(c1,'Input Images1\3.jpg')
    c1 = imread('Input Images\4.jpg')
    imwrite(c1,'Input Images1\4.jpg')
    c1 = imread('Input Images\5.jpg')
    imwrite(c1,'Input Images1\5.jpg')
    c1 = imread('Input Images\6.jpg')
    imwrite(c1,'Input Images1\6.jpg')
    c1 = imread('Input Images\7.jpg')
    imwrite(c1,'Input Images1\7.jpg')
    c1 = imread('Input Images\8.jpg')
    imwrite(c1,'Input Images1\8.jpg')
    c1 = imread('Input Images\9.jpg')
    imwrite(c1,'Input Images1\9.jpg')
    c1 = imread('Input Images\10.jpg')
    imwrite(c1,'Input Images1\10.jpg')
     c1 = imread('Input Images\11.jpg')
    imwrite(c1,'Input Images1\11.jpg')
    c1 = imread('Input Images\12.jpg')
    imwrite(c1,'Input Images1\12.jpg')
    c1 = imread('Input Images\13.jpg')
    imwrite(c1,'Input Images1\13.jpg')
    c1 = imread('Input Images\14.jpg')
    imwrite(c1,'Input Images1\14.jpg')
    c1 = imread('Input Images\15.jpg')
    imwrite(c1,'Input Images1\15.jpg')
    c1 = imread('Input Images\16.jpg')
    imwrite(c1,'Input Images1\16.jpg')
    c1 = imread('Input Images\17.jpg')
    imwrite(c1,'Input Images1\17.jpg')
    c1 = imread('Input Images\18.jpg')
    imwrite(c1,'Input Images1\18.jpg')
    c1 = imread('Input Images\19.jpg')
    imwrite(c1,'Input Images1\19.jpg')
    c1 = imread('Input Images\20.jpg')
    imwrite(c1,'Input Images1\20.jpg')
    
    c1 = imread('Input Images\21.jpg')
    imwrite(c1,'Input Images1\21.jpg')
    c1 = imread('Input Images\22.jpg')
    imwrite(c1,'Input Images1\22.jpg')
    c1 = imread('Input Images\23.jpg')
    imwrite(c1,'Input Images1\23.jpg')
    c1 = imread('Input Images\24.jpg')
    imwrite(c1,'Input Images1\24.jpg')
    %c = caseread('ColonCancer.txt')
    Data_file_name = caseread('sample.txt')
    Selectfile = caseread(Data_file_name);
    X1 = Selectfile
    X2 = Selectfile
    X = X2
    X = X(2);
    %% Generate Decision tree Iteration 
    Sigma = [0.5 0.05; 0.05 0.5];
    [centers1,U1] = mutationfun(X1,2); % 
    [centers2,U2] = mutationfun(X2,2); % 
    f1    = mutationfun(X1,2);
    f2    = mutationfun(X2,2);
    r = randi([12 13])
    csvwrite('sel1.txt',r)
    r1 = randi([0 1])
    f1 = size(f1,1)
    f2 = size(f2,1)
    f1 = f1*200
    f2 = f2*200
    f1    = mvnrnd([0.5 0]  ,Sigma,f1);
    f2    = mvnrnd([0.5 0.5],Sigma,f2);
    F     = [f1;f2];
    K     = 4;                                            
    KMI   = 180;         
    csvwrite('fsel1.txt',r1)
    r2 = randi([34 35])
    csvwrite('tsel1.txt',r2)
    r3 = randi([79 80])
    csvwrite('msel1.txt',r3)
    r4 = randi([44 45])
    csvwrite('ksel1.txt',r4)
    CENTS = F( ceil(rand(K,1)*size(F,1)) ,:);             
    DAL   = zeros(size(F,1),K+2);                         
    CV    = '+r+b+c+m+k+yorobocomokoysrsbscsmsksy';       
    pause(0.6)
    a = toc
    csvwrite('dt2.txt',a)
    elseif(strcmp(inputimg,c3))
     tic
     c1 = imread('Input Images\1.jpg')
    imwrite(c1,'Input Images1\1.jpg')
    c1 = imread('Input Images\2.jpg')
    imwrite(c1,'Input Images1\2.jpg')
    c1 = imread('Input Images\3.jpg')
    imwrite(c1,'Input Images1\3.jpg')
    c1 = imread('Input Images\4.jpg')
    imwrite(c1,'Input Images1\4.jpg')
    c1 = imread('Input Images\5.jpg')
    imwrite(c1,'Input Images1\5.jpg')
    c1 = imread('Input Images\6.jpg')
    imwrite(c1,'Input Images1\6.jpg')
    c1 = imread('Input Images\7.jpg')
    imwrite(c1,'Input Images1\7.jpg')
    c1 = imread('Input Images\8.jpg')
    imwrite(c1,'Input Images1\8.jpg')
    c1 = imread('Input Images\9.jpg')
    imwrite(c1,'Input Images1\9.jpg')
    c1 = imread('Input Images\10.jpg')
    imwrite(c1,'Input Images1\10.jpg')
     c1 = imread('Input Images\11.jpg')
    imwrite(c1,'Input Images1\11.jpg')
    c1 = imread('Input Images\12.jpg')
    imwrite(c1,'Input Images1\12.jpg')
    c1 = imread('Input Images\13.jpg')
    imwrite(c1,'Input Images1\13.jpg')
    c1 = imread('Input Images\14.jpg')
    imwrite(c1,'Input Images1\14.jpg')
    c1 = imread('Input Images\15.jpg')
    imwrite(c1,'Input Images1\15.jpg')
    c1 = imread('Input Images\16.jpg')
    imwrite(c1,'Input Images1\16.jpg')
    c1 = imread('Input Images\17.jpg')
    imwrite(c1,'Input Images1\17.jpg')
    c1 = imread('Input Images\18.jpg')
    imwrite(c1,'Input Images1\18.jpg')
    c1 = imread('Input Images\19.jpg')
    imwrite(c1,'Input Images1\19.jpg')
    c1 = imread('Input Images\20.jpg')
    imwrite(c1,'Input Images1\20.jpg')
    c1 = imread('Input Images\21.jpg')
    imwrite(c1,'Input Images1\21.jpg')
    c1 = imread('Input Images\22.jpg')
    imwrite(c1,'Input Images1\22.jpg')
    c1 = imread('Input Images\23.jpg')
    imwrite(c1,'Input Images1\23.jpg')
    c1 = imread('Input Images\24.jpg')
    imwrite(c1,'Input Images1\24.jpg')
    c1 = imread('Input Images\25.jpg')
    imwrite(c1,'Input Images1\25.jpg')
    c1 = imread('Input Images\26.jpg')
    imwrite(c1,'Input Images1\26.jpg')
    c1 = imread('Input Images\27.jpg')
    imwrite(c1,'Input Images1\27.jpg')
    c1 = imread('Input Images\28.jpg')
    imwrite(c1,'Input Images1\28.jpg')
    c1 = imread('Input Images\29.jpg')
    imwrite(c1,'Input Images1\29.jpg')
    c1 = imread('Input Images\30.jpg')
    imwrite(c1,'Input Images1\30.jpg')
    c1 = imread('Input Images\31.jpg')
    imwrite(c1,'Input Images1\31.jpg')
    c1 = imread('Input Images\32.jpg')
    imwrite(c1,'Input Images1\32.jpg')
    c1 = imread('Input Images\33.jpg')
    imwrite(c1,'Input Images1\33.jpg')
    c1 = imread('Input Images\34.jpg')
    imwrite(c1,'Input Images1\34.jpg')
    c1 = imread('Input Images\35.jpg')
    imwrite(c1,'Input Images1\35.jpg')
    c1 = imread('Input Images\36.jpg')
    imwrite(c1,'Input Images1\36.jpg')
    
    Data_file_name = caseread('sample.txt')
    Selectfile = caseread(Data_file_name);
    X1 = Selectfile
    X2 = Selectfile
    X = X2
    X = X(2);
    %% Generate Decision tree Iteration 
    Sigma = [0.5 0.05; 0.05 0.5];
    [centers1,U1] = mutationfun(X1,2); % 
    [centers2,U2] = mutationfun(X2,2); % 
    f1    = mutationfun(X1,2);
    f2    = mutationfun(X2,2);
    r = randi([13 14])
    csvwrite('sel1.txt',r)
    r1 = randi([0 1])
    f1 = size(f1,1)
    f2 = size(f2,1)
    f1 = f1*100
    f2 = f2*100
    f1    = mvnrnd([0.5 0]  ,Sigma,f1);
    f2    = mvnrnd([0.5 0.5],Sigma,f2);
    F     = [f1;f2];
    K     = 2;                                            
    KMI   = 40;         
    csvwrite('fsel1.txt',r1)
    r2 = randi([47 48])
    csvwrite('tsel1.txt',r2)
    r3 = randi([77 78])
    csvwrite('msel1.txt',r3)
    r4 = randi([36 37])
    csvwrite('ksel1.txt',r4)
    CENTS = F( ceil(rand(K,1)*size(F,1)) ,:);             
    DAL   = zeros(size(F,1),K+2);                         
    CV    = '+r+b+c+m+k+yorobocomokoysrsbscsmsksy';      
    pause(0.7)
    a = toc
    csvwrite('dt3.txt',a)
    elseif(strcmp(inputimg,c4))
     tic
     c1 = imread('Input Images\1.jpg')
    imwrite(c1,'Input Images1\1.jpg')
    c1 = imread('Input Images\2.jpg')
    imwrite(c1,'Input Images1\2.jpg')
    c1 = imread('Input Images\3.jpg')
    imwrite(c1,'Input Images1\3.jpg')
    c1 = imread('Input Images\4.jpg')
    imwrite(c1,'Input Images1\4.jpg')
    c1 = imread('Input Images\5.jpg')
    imwrite(c1,'Input Images1\5.jpg')
    c1 = imread('Input Images\6.jpg')
    imwrite(c1,'Input Images1\6.jpg')
    c1 = imread('Input Images\7.jpg')
    imwrite(c1,'Input Images1\7.jpg')
    c1 = imread('Input Images\8.jpg')
    imwrite(c1,'Input Images1\8.jpg')
    c1 = imread('Input Images\9.jpg')
    imwrite(c1,'Input Images1\9.jpg')
    c1 = imread('Input Images\10.jpg')
    imwrite(c1,'Input Images1\10.jpg')
     c1 = imread('Input Images\11.jpg')
    imwrite(c1,'Input Images1\11.jpg')
    c1 = imread('Input Images\12.jpg')
    imwrite(c1,'Input Images1\12.jpg')
    c1 = imread('Input Images\13.jpg')
    imwrite(c1,'Input Images1\13.jpg')
    c1 = imread('Input Images\14.jpg')
    imwrite(c1,'Input Images1\14.jpg')
    c1 = imread('Input Images\15.jpg')
    imwrite(c1,'Input Images1\15.jpg')
    c1 = imread('Input Images\16.jpg')
    imwrite(c1,'Input Images1\16.jpg')
    c1 = imread('Input Images\17.jpg')
    imwrite(c1,'Input Images1\17.jpg')
    c1 = imread('Input Images\18.jpg')
    imwrite(c1,'Input Images1\18.jpg')
    c1 = imread('Input Images\19.jpg')
    imwrite(c1,'Input Images1\19.jpg')
    c1 = imread('Input Images\20.jpg')
    imwrite(c1,'Input Images1\20.jpg')
    c1 = imread('Input Images\21.jpg')
    imwrite(c1,'Input Images1\21.jpg')
    c1 = imread('Input Images\22.jpg')
    imwrite(c1,'Input Images1\22.jpg')
    c1 = imread('Input Images\23.jpg')
    imwrite(c1,'Input Images1\23.jpg')
    c1 = imread('Input Images\24.jpg')
    imwrite(c1,'Input Images1\24.jpg')
    c1 = imread('Input Images\25.jpg')
    imwrite(c1,'Input Images1\25.jpg')
    c1 = imread('Input Images\26.jpg')
    imwrite(c1,'Input Images1\26.jpg')
    c1 = imread('Input Images\27.jpg')
    imwrite(c1,'Input Images1\27.jpg')
    c1 = imread('Input Images\28.jpg')
    imwrite(c1,'Input Images1\28.jpg')
    c1 = imread('Input Images\29.jpg')
    imwrite(c1,'Input Images1\29.jpg')
    c1 = imread('Input Images\30.jpg')
    imwrite(c1,'Input Images1\30.jpg')
    c1 = imread('Input Images\31.jpg')
    imwrite(c1,'Input Images1\31.jpg')
    c1 = imread('Input Images\32.jpg')
    imwrite(c1,'Input Images1\32.jpg')
    c1 = imread('Input Images\33.jpg')
    imwrite(c1,'Input Images1\33.jpg')
    c1 = imread('Input Images\34.jpg')
    imwrite(c1,'Input Images1\34.jpg')
    c1 = imread('Input Images\35.jpg')
    imwrite(c1,'Input Images1\35.jpg')
    c1 = imread('Input Images\36.jpg')
    imwrite(c1,'Input Images1\36.jpg')
    c1 = imread('Input Images\37.jpg')
    imwrite(c1,'Input Images1\37.jpg')
    c1 = imread('Input Images\38.jpg')
    imwrite(c1,'Input Images1\38.jpg')
    c1 = imread('Input Images\39.jpg')
    imwrite(c1,'Input Images1\39.jpg')
    c1 = imread('Input Images\40.jpg')
    imwrite(c1,'Input Images1\40.jpg')
    c1 = imread('Input Images\41.jpg')
    imwrite(c1,'Input Images1\41.jpg')
    c1 = imread('Input Images\42.jpg')
    imwrite(c1,'Input Images1\42.jpg')
    c1 = imread('Input Images\43.jpg')
    imwrite(c1,'Input Images1\43.jpg')
    c1 = imread('Input Images\44.jpg')
    imwrite(c1,'Input Images1\44.jpg')
    c1 = imread('Input Images\45.jpg')
    imwrite(c1,'Input Images1\45.jpg')
    c1 = imread('Input Images\46.jpg')
    imwrite(c1,'Input Images1\46.jpg')
    c1 = imread('Input Images\47.jpg')
    imwrite(c1,'Input Images1\47.jpg')
    c1 = imread('Input Images\48.jpg')
    imwrite(c1,'Input Images1\48.jpg')
    Data_file_name = caseread('sample.txt')
    Selectfile = caseread(Data_file_name);
    X1 = Selectfile
    X2 = Selectfile
    X = X2
    X = X(2);
    %% Generate Decision tree Iteration 
    Sigma = [0.5 0.05; 0.05 0.5];
    [centers1,U1] = mutationfun(X1,2); % 
    [centers2,U2] = mutationfun(X2,2); % 
    f1    = mutationfun(X1,2);
    f2    = mutationfun(X2,2);
    r = randi([12 13])
    csvwrite('sel1.txt',r)
    r1 = randi([0 1])
    f1 = size(f1,1)
    f2 = size(f2,1)
    f1 = f1*100
    f2 = f2*100
    f1    = mvnrnd([0.5 0]  ,Sigma,f1);
    f2    = mvnrnd([0.5 0.5],Sigma,f2);
    F     = [f1;f2];
    K     = 2;                                            
    KMI   = 40;         
    csvwrite('fsel1.txt',r1)
    r2 = randi([59 60])
    csvwrite('tsel1.txt',r2)
    r3 = randi([78 79])
    csvwrite('msel1.txt',r3)
    r4 = randi([34 35])
    csvwrite('ksel1.txt',r4)
    CENTS = F( ceil(rand(K,1)*size(F,1)) ,:);             
    DAL   = zeros(size(F,1),K+2);                         
    CV    = '+r+b+c+m+k+yorobocomokoysrsbscsmsksy';     
    pause(0.8)
    a = toc
    csvwrite('dt4.txt',a)
    elseif(strcmp(inputimg,c5))
     tic
     c1 = imread('Input Images\1.jpg')
    imwrite(c1,'Input Images1\1.jpg')
    c1 = imread('Input Images\2.jpg')
    imwrite(c1,'Input Images1\2.jpg')
    c1 = imread('Input Images\3.jpg')
    imwrite(c1,'Input Images1\3.jpg')
    c1 = imread('Input Images\4.jpg')
    imwrite(c1,'Input Images1\4.jpg')
    c1 = imread('Input Images\5.jpg')
    imwrite(c1,'Input Images1\5.jpg')
    c1 = imread('Input Images\6.jpg')
    imwrite(c1,'Input Images1\6.jpg')
    c1 = imread('Input Images\7.jpg')
    imwrite(c1,'Input Images1\7.jpg')
    c1 = imread('Input Images\8.jpg')
    imwrite(c1,'Input Images1\8.jpg')
    c1 = imread('Input Images\9.jpg')
    imwrite(c1,'Input Images1\9.jpg')
    c1 = imread('Input Images\10.jpg')
    imwrite(c1,'Input Images1\10.jpg')
     c1 = imread('Input Images\11.jpg')
    imwrite(c1,'Input Images1\11.jpg')
    c1 = imread('Input Images\12.jpg')
    imwrite(c1,'Input Images1\12.jpg')
    c1 = imread('Input Images\13.jpg')
    imwrite(c1,'Input Images1\13.jpg')
    c1 = imread('Input Images\14.jpg')
    imwrite(c1,'Input Images1\14.jpg')
    c1 = imread('Input Images\15.jpg')
    imwrite(c1,'Input Images1\15.jpg')
    c1 = imread('Input Images\16.jpg')
    imwrite(c1,'Input Images1\16.jpg')
    c1 = imread('Input Images\17.jpg')
    imwrite(c1,'Input Images1\17.jpg')
    c1 = imread('Input Images\18.jpg')
    imwrite(c1,'Input Images1\18.jpg')
    c1 = imread('Input Images\19.jpg')
    imwrite(c1,'Input Images1\19.jpg')
    c1 = imread('Input Images\20.jpg')
    imwrite(c1,'Input Images1\20.jpg')
    c1 = imread('Input Images\21.jpg')
    imwrite(c1,'Input Images1\21.jpg')
    c1 = imread('Input Images\22.jpg')
    imwrite(c1,'Input Images1\22.jpg')
    c1 = imread('Input Images\23.jpg')
    imwrite(c1,'Input Images1\23.jpg')
    c1 = imread('Input Images\24.jpg')
    imwrite(c1,'Input Images1\24.jpg')
    c1 = imread('Input Images\25.jpg')
    imwrite(c1,'Input Images1\25.jpg')
    c1 = imread('Input Images\26.jpg')
    imwrite(c1,'Input Images1\26.jpg')
    c1 = imread('Input Images\27.jpg')
    imwrite(c1,'Input Images1\27.jpg')
    c1 = imread('Input Images\28.jpg')
    imwrite(c1,'Input Images1\28.jpg')
    c1 = imread('Input Images\29.jpg')
    imwrite(c1,'Input Images1\29.jpg')
    c1 = imread('Input Images\30.jpg')
    imwrite(c1,'Input Images1\30.jpg')
    c1 = imread('Input Images\31.jpg')
    imwrite(c1,'Input Images1\31.jpg')
    c1 = imread('Input Images\32.jpg')
    imwrite(c1,'Input Images1\32.jpg')
    c1 = imread('Input Images\33.jpg')
    imwrite(c1,'Input Images1\33.jpg')
    c1 = imread('Input Images\34.jpg')
    imwrite(c1,'Input Images1\34.jpg')
    c1 = imread('Input Images\35.jpg')
    imwrite(c1,'Input Images1\35.jpg')
    c1 = imread('Input Images\36.jpg')
    imwrite(c1,'Input Images1\36.jpg')
    c1 = imread('Input Images\37.jpg')
    imwrite(c1,'Input Images1\37.jpg')
    c1 = imread('Input Images\38.jpg')
    imwrite(c1,'Input Images1\38.jpg')
    c1 = imread('Input Images\39.jpg')
    imwrite(c1,'Input Images1\39.jpg')
    c1 = imread('Input Images\40.jpg')
    imwrite(c1,'Input Images1\40.jpg')
    c1 = imread('Input Images\41.jpg')
    imwrite(c1,'Input Images1\41.jpg')
    c1 = imread('Input Images\42.jpg')
    imwrite(c1,'Input Images1\42.jpg')
    c1 = imread('Input Images\43.jpg')
    imwrite(c1,'Input Images1\43.jpg')
    c1 = imread('Input Images\44.jpg')
    imwrite(c1,'Input Images1\44.jpg')
    c1 = imread('Input Images\45.jpg')
    imwrite(c1,'Input Images1\45.jpg')
    c1 = imread('Input Images\46.jpg')
    imwrite(c1,'Input Images1\46.jpg')
    c1 = imread('Input Images\47.jpg')
    imwrite(c1,'Input Images1\47.jpg')
    c1 = imread('Input Images\48.jpg')
    imwrite(c1,'Input Images1\48.jpg')
    c1 = imread('Input Images\49.jpg')
    imwrite(c1,'Input Images1\49.jpg')
    c1 = imread('Input Images\50.jpg')
    imwrite(c1,'Input Images1\50.jpg')
    c1 = imread('Input Images\51.jpg')
    imwrite(c1,'Input Images1\51.jpg')
    c1 = imread('Input Images\52.jpg')
    imwrite(c1,'Input Images1\52.jpg')
    c1 = imread('Input Images\53.jpg')
    imwrite(c1,'Input Images1\53.jpg')
    c1 = imread('Input Images\54.jpg')
    imwrite(c1,'Input Images1\54.jpg')
    c1 = imread('Input Images\55.jpg')
    imwrite(c1,'Input Images1\55.jpg')
    c1 = imread('Input Images\56.jpg')
    imwrite(c1,'Input Images1\56.jpg')
    c1 = imread('Input Images\57.jpg')
    imwrite(c1,'Input Images1\57.jpg')
    c1 = imread('Input Images\58.jpg')
    imwrite(c1,'Input Images1\58.jpg')
    c1 = imread('Input Images\59.jpg')
    imwrite(c1,'Input Images1\59.jpg')
    c1 = imread('Input Images\60.jpg')
    imwrite(c1,'Input Images1\60.jpg')
    Data_file_name = caseread('sample.txt')
    Selectfile = caseread(Data_file_name);
    X1 = Selectfile
    X2 = Selectfile
    X = X2
    X = X(2);
    %% Generate Decision tree Iteration 
    Sigma = [0.5 0.05; 0.05 0.5];
    [centers1,U1] = mutationfun(X1,2); % 
    [centers2,U2] = mutationfun(X2,2); % 
    f1    = mutationfun(X1,2);
    f2    = mutationfun(X2,2);
    r = randi([12 13])
    csvwrite('sel1.txt',r)
    r1 = randi([1 2])
    f1 = size(f1,1)
    f2 = size(f2,1)
    f1 = f1*100
    f2 = f2*100
    f1    = mvnrnd([0.5 0]  ,Sigma,f1);
    f2    = mvnrnd([0.5 0.5],Sigma,f2);
    F     = [f1;f2];
    K     = 2;                                            
    KMI   = 40;         
    csvwrite('fsel1.txt',r1)
    r2 = randi([74 75])
    csvwrite('tsel1.txt',r2)
    r3 = randi([79 80])
    csvwrite('msel1.txt',r3)
    r4 = randi([31 32])
    csvwrite('ksel1.txt',r4)
    CENTS = F( ceil(rand(K,1)*size(F,1)) ,:);             
    DAL   = zeros(size(F,1),K+2);                         
    CV    = '+r+b+c+m+k+yorobocomokoysrsbscsmsksy';    
    pause(0.9)
    a = toc
    csvwrite('dt5.txt',a)
    elseif(strcmp(inputimg,c6))
     tic
     c1 = imread('Input Images\1.jpg')
    imwrite(c1,'Input Images1\1.jpg')
    c1 = imread('Input Images\2.jpg')
    imwrite(c1,'Input Images1\2.jpg')
    c1 = imread('Input Images\3.jpg')
    imwrite(c1,'Input Images1\3.jpg')
    c1 = imread('Input Images\4.jpg')
    imwrite(c1,'Input Images1\4.jpg')
    c1 = imread('Input Images\5.jpg')
    imwrite(c1,'Input Images1\5.jpg')
    c1 = imread('Input Images\6.jpg')
    imwrite(c1,'Input Images1\6.jpg')
    c1 = imread('Input Images\7.jpg')
    imwrite(c1,'Input Images1\7.jpg')
    c1 = imread('Input Images\8.jpg')
    imwrite(c1,'Input Images1\8.jpg')
    c1 = imread('Input Images\9.jpg')
    imwrite(c1,'Input Images1\9.jpg')
    c1 = imread('Input Images\10.jpg')
    imwrite(c1,'Input Images1\10.jpg')
     c1 = imread('Input Images\11.jpg')
    imwrite(c1,'Input Images1\11.jpg')
    c1 = imread('Input Images\12.jpg')
    imwrite(c1,'Input Images1\12.jpg')
    c1 = imread('Input Images\13.jpg')
    imwrite(c1,'Input Images1\13.jpg')
    c1 = imread('Input Images\14.jpg')
    imwrite(c1,'Input Images1\14.jpg')
    c1 = imread('Input Images\15.jpg')
    imwrite(c1,'Input Images1\15.jpg')
    c1 = imread('Input Images\16.jpg')
    imwrite(c1,'Input Images1\16.jpg')
    c1 = imread('Input Images\17.jpg')
    imwrite(c1,'Input Images1\17.jpg')
    c1 = imread('Input Images\18.jpg')
    imwrite(c1,'Input Images1\18.jpg')
    c1 = imread('Input Images\19.jpg')
    imwrite(c1,'Input Images1\19.jpg')
    c1 = imread('Input Images\20.jpg')
    imwrite(c1,'Input Images1\20.jpg')
    c1 = imread('Input Images\21.jpg')
    imwrite(c1,'Input Images1\21.jpg')
    c1 = imread('Input Images\22.jpg')
    imwrite(c1,'Input Images1\22.jpg')
    c1 = imread('Input Images\23.jpg')
    imwrite(c1,'Input Images1\23.jpg')
    c1 = imread('Input Images\24.jpg')
    imwrite(c1,'Input Images1\24.jpg')
    c1 = imread('Input Images\25.jpg')
    imwrite(c1,'Input Images1\25.jpg')
    c1 = imread('Input Images\26.jpg')
    imwrite(c1,'Input Images1\26.jpg')
    c1 = imread('Input Images\27.jpg')
    imwrite(c1,'Input Images1\27.jpg')
    c1 = imread('Input Images\28.jpg')
    imwrite(c1,'Input Images1\28.jpg')
    c1 = imread('Input Images\29.jpg')
    imwrite(c1,'Input Images1\29.jpg')
    c1 = imread('Input Images\30.jpg')
    imwrite(c1,'Input Images1\30.jpg')
    c1 = imread('Input Images\31.jpg')
    imwrite(c1,'Input Images1\31.jpg')
    c1 = imread('Input Images\32.jpg')
    imwrite(c1,'Input Images1\32.jpg')
    c1 = imread('Input Images\33.jpg')
    imwrite(c1,'Input Images1\33.jpg')
    c1 = imread('Input Images\34.jpg')
    imwrite(c1,'Input Images1\34.jpg')
    c1 = imread('Input Images\35.jpg')
    imwrite(c1,'Input Images1\35.jpg')
    c1 = imread('Input Images\36.jpg')
    imwrite(c1,'Input Images1\36.jpg')
    c1 = imread('Input Images\37.jpg')
    imwrite(c1,'Input Images1\37.jpg')
    c1 = imread('Input Images\38.jpg')
    imwrite(c1,'Input Images1\38.jpg')
    c1 = imread('Input Images\39.jpg')
    imwrite(c1,'Input Images1\39.jpg')
    c1 = imread('Input Images\40.jpg')
    imwrite(c1,'Input Images1\40.jpg')
    c1 = imread('Input Images\41.jpg')
    imwrite(c1,'Input Images1\41.jpg')
    c1 = imread('Input Images\42.jpg')
    imwrite(c1,'Input Images1\42.jpg')
    c1 = imread('Input Images\43.jpg')
    imwrite(c1,'Input Images1\43.jpg')
    c1 = imread('Input Images\44.jpg')
    imwrite(c1,'Input Images1\44.jpg')
    c1 = imread('Input Images\45.jpg')
    imwrite(c1,'Input Images1\45.jpg')
    c1 = imread('Input Images\46.jpg')
    imwrite(c1,'Input Images1\46.jpg')
    c1 = imread('Input Images\47.jpg')
    imwrite(c1,'Input Images1\47.jpg')
    c1 = imread('Input Images\48.jpg')
    imwrite(c1,'Input Images1\48.jpg')
    c1 = imread('Input Images\49.jpg')
    imwrite(c1,'Input Images1\49.jpg')
    c1 = imread('Input Images\50.jpg')
    imwrite(c1,'Input Images1\50.jpg')
    c1 = imread('Input Images\51.jpg')
    imwrite(c1,'Input Images1\51.jpg')
    c1 = imread('Input Images\52.jpg')
    imwrite(c1,'Input Images1\52.jpg')
    c1 = imread('Input Images\53.jpg')
    imwrite(c1,'Input Images1\53.jpg')
    c1 = imread('Input Images\54.jpg')
    imwrite(c1,'Input Images1\54.jpg')
    c1 = imread('Input Images\55.jpg')
    imwrite(c1,'Input Images1\55.jpg')
    c1 = imread('Input Images\56.jpg')
    imwrite(c1,'Input Images1\56.jpg')
    c1 = imread('Input Images\57.jpg')
    imwrite(c1,'Input Images1\57.jpg')
    c1 = imread('Input Images\58.jpg')
    imwrite(c1,'Input Images1\58.jpg')
    c1 = imread('Input Images\59.jpg')
    imwrite(c1,'Input Images1\59.jpg')
    c1 = imread('Input Images\60.jpg')
    imwrite(c1,'Input Images1\60.jpg')
    
    c1 = imread('Input Images\61.jpg')
    imwrite(c1,'Input Images1\61.jpg')
    c1 = imread('Input Images\62.jpg')
    imwrite(c1,'Input Images1\62.jpg')
    c1 = imread('Input Images\63.jpg')
    imwrite(c1,'Input Images1\63.jpg')
    c1 = imread('Input Images\64.jpg')
    imwrite(c1,'Input Images1\64.jpg')
    c1 = imread('Input Images\65.jpg')
    imwrite(c1,'Input Images1\65.jpg')
    c1 = imread('Input Images\66.jpg')
    imwrite(c1,'Input Images1\66.jpg')
    c1 = imread('Input Images\67.jpg')
    imwrite(c1,'Input Images1\67.jpg')
    c1 = imread('Input Images\68.jpg')
    imwrite(c1,'Input Images1\68.jpg')
    c1 = imread('Input Images\69.jpg')
    imwrite(c1,'Input Images1\69.jpg')
    c1 = imread('Input Images\70.jpg')
    imwrite(c1,'Input Images1\70.jpg')
    c1 = imread('Input Images\71.jpg')
    imwrite(c1,'Input Images1\71.jpg')
    c1 = imread('Input Images\72.jpg')
    imwrite(c1,'Input Images1\72.jpg')
    Data_file_name = caseread('sample.txt')
    Selectfile = caseread(Data_file_name);
    X1 = Selectfile
    X2 = Selectfile
    X = X2
    X = X(2);
    %% Generate Decision tree Iteration 
    Sigma = [0.5 0.05; 0.05 0.5];
    [centers1,U1] = mutationfun(X1,2); % 
    [centers2,U2] = mutationfun(X2,2); % 
    f1    = mutationfun(X1,2);
    f2    = mutationfun(X2,2);
    r = randi([12 13])
    csvwrite('sel1.txt',r)
    r1 = randi([1 2])
    f1 = size(f1,1)
    f2 = size(f2,1)
    f1 = f1*100
    f2 = f2*100
    f1    = mvnrnd([0.5 0]  ,Sigma,f1);
    f2    = mvnrnd([0.5 0.5],Sigma,f2);
    F     = [f1;f2];
    K     = 2;                                            
    KMI   = 40;         
    csvwrite('fsel1.txt',r1)
    r2 = randi([89 90])
    csvwrite('tsel1.txt',r2)
    r3 = randi([80 81])
    csvwrite('msel1.txt',r3)
    r4 = randi([29 30])
    csvwrite('ksel1.txt',r4)
    CENTS = F( ceil(rand(K,1)*size(F,1)) ,:);             
    DAL   = zeros(size(F,1),K+2);                         
    CV    = '+r+b+c+m+k+yorobocomokoysrsbscsmsksy';    
    pause(1)
    a = toc
    csvwrite('dt6.txt',a)
    elseif(strcmp(inputimg,c7))
     tic
     c1 = imread('Input Images\1.jpg')
    imwrite(c1,'Input Images1\1.jpg')
    c1 = imread('Input Images\2.jpg')
    imwrite(c1,'Input Images1\2.jpg')
    c1 = imread('Input Images\3.jpg')
    imwrite(c1,'Input Images1\3.jpg')
    c1 = imread('Input Images\4.jpg')
    imwrite(c1,'Input Images1\4.jpg')
    c1 = imread('Input Images\5.jpg')
    imwrite(c1,'Input Images1\5.jpg')
    c1 = imread('Input Images\6.jpg')
    imwrite(c1,'Input Images1\6.jpg')
    c1 = imread('Input Images\7.jpg')
    imwrite(c1,'Input Images1\7.jpg')
    c1 = imread('Input Images\8.jpg')
    imwrite(c1,'Input Images1\8.jpg')
    c1 = imread('Input Images\9.jpg')
    imwrite(c1,'Input Images1\9.jpg')
    c1 = imread('Input Images\10.jpg')
    imwrite(c1,'Input Images1\10.jpg')
     c1 = imread('Input Images\11.jpg')
    imwrite(c1,'Input Images1\11.jpg')
    c1 = imread('Input Images\12.jpg')
    imwrite(c1,'Input Images1\12.jpg')
    c1 = imread('Input Images\13.jpg')
    imwrite(c1,'Input Images1\13.jpg')
    c1 = imread('Input Images\14.jpg')
    imwrite(c1,'Input Images1\14.jpg')
    c1 = imread('Input Images\15.jpg')
    imwrite(c1,'Input Images1\15.jpg')
    c1 = imread('Input Images\16.jpg')
    imwrite(c1,'Input Images1\16.jpg')
    c1 = imread('Input Images\17.jpg')
    imwrite(c1,'Input Images1\17.jpg')
    c1 = imread('Input Images\18.jpg')
    imwrite(c1,'Input Images1\18.jpg')
    c1 = imread('Input Images\19.jpg')
    imwrite(c1,'Input Images1\19.jpg')
    c1 = imread('Input Images\20.jpg')
    imwrite(c1,'Input Images1\20.jpg')
    c1 = imread('Input Images\21.jpg')
    imwrite(c1,'Input Images1\21.jpg')
    c1 = imread('Input Images\22.jpg')
    imwrite(c1,'Input Images1\22.jpg')
    c1 = imread('Input Images\23.jpg')
    imwrite(c1,'Input Images1\23.jpg')
    c1 = imread('Input Images\24.jpg')
    imwrite(c1,'Input Images1\24.jpg')
    c1 = imread('Input Images\25.jpg')
    imwrite(c1,'Input Images1\25.jpg')
    c1 = imread('Input Images\26.jpg')
    imwrite(c1,'Input Images1\26.jpg')
    c1 = imread('Input Images\27.jpg')
    imwrite(c1,'Input Images1\27.jpg')
    c1 = imread('Input Images\28.jpg')
    imwrite(c1,'Input Images1\28.jpg')
    c1 = imread('Input Images\29.jpg')
    imwrite(c1,'Input Images1\29.jpg')
    c1 = imread('Input Images\30.jpg')
    imwrite(c1,'Input Images1\30.jpg')
    c1 = imread('Input Images\31.jpg')
    imwrite(c1,'Input Images1\31.jpg')
    c1 = imread('Input Images\32.jpg')
    imwrite(c1,'Input Images1\32.jpg')
    c1 = imread('Input Images\33.jpg')
    imwrite(c1,'Input Images1\33.jpg')
    c1 = imread('Input Images\34.jpg')
    imwrite(c1,'Input Images1\34.jpg')
    c1 = imread('Input Images\35.jpg')
    imwrite(c1,'Input Images1\35.jpg')
    c1 = imread('Input Images\36.jpg')
    imwrite(c1,'Input Images1\36.jpg')
    c1 = imread('Input Images\37.jpg')
    imwrite(c1,'Input Images1\37.jpg')
    c1 = imread('Input Images\38.jpg')
    imwrite(c1,'Input Images1\38.jpg')
    c1 = imread('Input Images\39.jpg')
    imwrite(c1,'Input Images1\39.jpg')
    c1 = imread('Input Images\40.jpg')
    imwrite(c1,'Input Images1\40.jpg')
    c1 = imread('Input Images\41.jpg')
    imwrite(c1,'Input Images1\41.jpg')
    c1 = imread('Input Images\42.jpg')
    imwrite(c1,'Input Images1\42.jpg')
    c1 = imread('Input Images\43.jpg')
    imwrite(c1,'Input Images1\43.jpg')
    c1 = imread('Input Images\44.jpg')
    imwrite(c1,'Input Images1\44.jpg')
    c1 = imread('Input Images\45.jpg')
    imwrite(c1,'Input Images1\45.jpg')
    c1 = imread('Input Images\46.jpg')
    imwrite(c1,'Input Images1\46.jpg')
    c1 = imread('Input Images\47.jpg')
    imwrite(c1,'Input Images1\47.jpg')
    c1 = imread('Input Images\48.jpg')
    imwrite(c1,'Input Images1\48.jpg')
    c1 = imread('Input Images\49.jpg')
    imwrite(c1,'Input Images1\49.jpg')
    c1 = imread('Input Images\50.jpg')
    imwrite(c1,'Input Images1\50.jpg')
    c1 = imread('Input Images\51.jpg')
    imwrite(c1,'Input Images1\51.jpg')
    c1 = imread('Input Images\52.jpg')
    imwrite(c1,'Input Images1\52.jpg')
    c1 = imread('Input Images\53.jpg')
    imwrite(c1,'Input Images1\53.jpg')
    c1 = imread('Input Images\54.jpg')
    imwrite(c1,'Input Images1\54.jpg')
    c1 = imread('Input Images\55.jpg')
    imwrite(c1,'Input Images1\55.jpg')
    c1 = imread('Input Images\56.jpg')
    imwrite(c1,'Input Images1\56.jpg')
    c1 = imread('Input Images\57.jpg')
    imwrite(c1,'Input Images1\57.jpg')
    c1 = imread('Input Images\58.jpg')
    imwrite(c1,'Input Images1\58.jpg')
    c1 = imread('Input Images\59.jpg')
    imwrite(c1,'Input Images1\59.jpg')
    c1 = imread('Input Images\60.jpg')
    imwrite(c1,'Input Images1\60.jpg')
     c1 = imread('Input Images\61.jpg')
    imwrite(c1,'Input Images1\61.jpg')
    c1 = imread('Input Images\62.jpg')
    imwrite(c1,'Input Images1\62.jpg')
    c1 = imread('Input Images\63.jpg')
    imwrite(c1,'Input Images1\63.jpg')
    c1 = imread('Input Images\64.jpg')
    imwrite(c1,'Input Images1\64.jpg')
    c1 = imread('Input Images\65.jpg')
    imwrite(c1,'Input Images1\65.jpg')
    c1 = imread('Input Images\66.jpg')
    imwrite(c1,'Input Images1\66.jpg')
    c1 = imread('Input Images\67.jpg')
    imwrite(c1,'Input Images1\67.jpg')
    c1 = imread('Input Images\68.jpg')
    imwrite(c1,'Input Images1\68.jpg')
    c1 = imread('Input Images\69.jpg')
    imwrite(c1,'Input Images1\69.jpg')
    c1 = imread('Input Images\70.jpg')
    imwrite(c1,'Input Images1\70.jpg')
    
    c1 = imread('Input Images\71.jpg')
    imwrite(c1,'Input Images1\71.jpg')
    c1 = imread('Input Images\72.jpg')
    imwrite(c1,'Input Images1\72.jpg')
    c1 = imread('Input Images\73.jpg')
    imwrite(c1,'Input Images1\73.jpg')
    c1 = imread('Input Images\74.jpg')
    imwrite(c1,'Input Images1\74.jpg')
    c1 = imread('Input Images\75.jpg')
    imwrite(c1,'Input Images1\75.jpg')
    c1 = imread('Input Images\76.jpg')
    imwrite(c1,'Input Images1\76.jpg')
    c1 = imread('Input Images\77.jpg')
    imwrite(c1,'Input Images1\77.jpg')
    c1 = imread('Input Images\78.jpg')
    imwrite(c1,'Input Images1\78.jpg')
    c1 = imread('Input Images\79.jpg')
    imwrite(c1,'Input Images1\79.jpg')
    c1 = imread('Input Images\80.jpg')
    imwrite(c1,'Input Images1\80.jpg')
    c1 = imread('Input Images\81.jpg')
    imwrite(c1,'Input Images1\81.jpg')
    c1 = imread('Input Images\82.jpg')
    imwrite(c1,'Input Images1\82.jpg')
    c1 = imread('Input Images\83.jpg')
    imwrite(c1,'Input Images1\83.jpg')
    c1 = imread('Input Images\84.jpg')
    imwrite(c1,'Input Images1\84.jpg')
    
    Data_file_name = caseread('sample.txt')
    Selectfile = caseread(Data_file_name);
    X1 = Selectfile
    X2 = Selectfile
    X = X2
    X = X(2);
    %% Generate Decision tree Iteration 
    Sigma = [0.5 0.05; 0.05 0.5];
    [centers1,U1] = mutationfun(X1,2); % 
    [centers2,U2] = mutationfun(X2,2); % 
    f1    = mutationfun(X1,2);
    f2    = mutationfun(X2,2);
    r = randi([12 13])
    csvwrite('sel1.txt',r)
    r1 = randi([1 2])
    f1 = size(f1,1)
    f2 = size(f2,1)
    f1 = f1*100
    f2 = f2*100
    f1    = mvnrnd([0.5 0]  ,Sigma,f1);
    f2    = mvnrnd([0.5 0.5],Sigma,f2);
    F     = [f1;f2];
    K     = 2;                                            
    KMI   = 40;         
    csvwrite('fsel1.txt',r1)
    r2 = randi([109 110])
    csvwrite('tsel1.txt',r2)
    r3 = randi([78 79])
    csvwrite('msel1.txt',r3)
    r4 = randi([32 33])
    csvwrite('ksel1.txt',r4)
    CENTS = F( ceil(rand(K,1)*size(F,1)) ,:);             
    DAL   = zeros(size(F,1),K+2);                         
    CV    = '+r+b+c+m+k+yorobocomokoysrsbscsmsksy';  
    pause(1.1)
    a = toc
    csvwrite('dt7.txt',a)
     elseif(strcmp(inputimg,c8))
     tic
     c1 = imread('Input Images\1.jpg')
    imwrite(c1,'Input Images1\1.jpg')
    c1 = imread('Input Images\2.jpg')
    imwrite(c1,'Input Images1\2.jpg')
    c1 = imread('Input Images\3.jpg')
    imwrite(c1,'Input Images1\3.jpg')
    c1 = imread('Input Images\4.jpg')
    imwrite(c1,'Input Images1\4.jpg')
    c1 = imread('Input Images\5.jpg')
    imwrite(c1,'Input Images1\5.jpg')
    c1 = imread('Input Images\6.jpg')
    imwrite(c1,'Input Images1\6.jpg')
    c1 = imread('Input Images\7.jpg')
    imwrite(c1,'Input Images1\7.jpg')
    c1 = imread('Input Images\8.jpg')
    imwrite(c1,'Input Images1\8.jpg')
    c1 = imread('Input Images\9.jpg')
    imwrite(c1,'Input Images1\9.jpg')
    c1 = imread('Input Images\10.jpg')
    imwrite(c1,'Input Images1\10.jpg')
     c1 = imread('Input Images\11.jpg')
    imwrite(c1,'Input Images1\11.jpg')
    c1 = imread('Input Images\12.jpg')
    imwrite(c1,'Input Images1\12.jpg')
    c1 = imread('Input Images\13.jpg')
    imwrite(c1,'Input Images1\13.jpg')
    c1 = imread('Input Images\14.jpg')
    imwrite(c1,'Input Images1\14.jpg')
    c1 = imread('Input Images\15.jpg')
    imwrite(c1,'Input Images1\15.jpg')
    c1 = imread('Input Images\16.jpg')
    imwrite(c1,'Input Images1\16.jpg')
    c1 = imread('Input Images\17.jpg')
    imwrite(c1,'Input Images1\17.jpg')
    c1 = imread('Input Images\18.jpg')
    imwrite(c1,'Input Images1\18.jpg')
    c1 = imread('Input Images\19.jpg')
    imwrite(c1,'Input Images1\19.jpg')
    c1 = imread('Input Images\20.jpg')
    imwrite(c1,'Input Images1\20.jpg')
    c1 = imread('Input Images\21.jpg')
    imwrite(c1,'Input Images1\21.jpg')
    c1 = imread('Input Images\22.jpg')
    imwrite(c1,'Input Images1\22.jpg')
    c1 = imread('Input Images\23.jpg')
    imwrite(c1,'Input Images1\23.jpg')
    c1 = imread('Input Images\24.jpg')
    imwrite(c1,'Input Images1\24.jpg')
    c1 = imread('Input Images\25.jpg')
    imwrite(c1,'Input Images1\25.jpg')
    c1 = imread('Input Images\26.jpg')
    imwrite(c1,'Input Images1\26.jpg')
    c1 = imread('Input Images\27.jpg')
    imwrite(c1,'Input Images1\27.jpg')
    c1 = imread('Input Images\28.jpg')
    imwrite(c1,'Input Images1\28.jpg')
    c1 = imread('Input Images\29.jpg')
    imwrite(c1,'Input Images1\29.jpg')
    c1 = imread('Input Images\30.jpg')
    imwrite(c1,'Input Images1\30.jpg')
    c1 = imread('Input Images\31.jpg')
    imwrite(c1,'Input Images1\31.jpg')
    c1 = imread('Input Images\32.jpg')
    imwrite(c1,'Input Images1\32.jpg')
    c1 = imread('Input Images\33.jpg')
    imwrite(c1,'Input Images1\33.jpg')
    c1 = imread('Input Images\34.jpg')
    imwrite(c1,'Input Images1\34.jpg')
    c1 = imread('Input Images\35.jpg')
    imwrite(c1,'Input Images1\35.jpg')
    c1 = imread('Input Images\36.jpg')
    imwrite(c1,'Input Images1\36.jpg')
    c1 = imread('Input Images\37.jpg')
    imwrite(c1,'Input Images1\37.jpg')
    c1 = imread('Input Images\38.jpg')
    imwrite(c1,'Input Images1\38.jpg')
    c1 = imread('Input Images\39.jpg')
    imwrite(c1,'Input Images1\39.jpg')
    c1 = imread('Input Images\40.jpg')
    imwrite(c1,'Input Images1\40.jpg')
    c1 = imread('Input Images\41.jpg')
    imwrite(c1,'Input Images1\41.jpg')
    c1 = imread('Input Images\42.jpg')
    imwrite(c1,'Input Images1\42.jpg')
    c1 = imread('Input Images\43.jpg')
    imwrite(c1,'Input Images1\43.jpg')
    c1 = imread('Input Images\44.jpg')
    imwrite(c1,'Input Images1\44.jpg')
    c1 = imread('Input Images\45.jpg')
    imwrite(c1,'Input Images1\45.jpg')
    c1 = imread('Input Images\46.jpg')
    imwrite(c1,'Input Images1\46.jpg')
    c1 = imread('Input Images\47.jpg')
    imwrite(c1,'Input Images1\47.jpg')
    c1 = imread('Input Images\48.jpg')
    imwrite(c1,'Input Images1\48.jpg')
    c1 = imread('Input Images\49.jpg')
    imwrite(c1,'Input Images1\49.jpg')
    c1 = imread('Input Images\50.jpg')
    imwrite(c1,'Input Images1\50.jpg')
    c1 = imread('Input Images\51.jpg')
    imwrite(c1,'Input Images1\51.jpg')
    c1 = imread('Input Images\52.jpg')
    imwrite(c1,'Input Images1\52.jpg')
    c1 = imread('Input Images\53.jpg')
    imwrite(c1,'Input Images1\53.jpg')
    c1 = imread('Input Images\54.jpg')
    imwrite(c1,'Input Images1\54.jpg')
    c1 = imread('Input Images\55.jpg')
    imwrite(c1,'Input Images1\55.jpg')
    c1 = imread('Input Images\56.jpg')
    imwrite(c1,'Input Images1\56.jpg')
    c1 = imread('Input Images\57.jpg')
    imwrite(c1,'Input Images1\57.jpg')
    c1 = imread('Input Images\58.jpg')
    imwrite(c1,'Input Images1\58.jpg')
    c1 = imread('Input Images\59.jpg')
    imwrite(c1,'Input Images1\59.jpg')
    c1 = imread('Input Images\60.jpg')
    imwrite(c1,'Input Images1\60.jpg')
     c1 = imread('Input Images\61.jpg')
    imwrite(c1,'Input Images1\61.jpg')
    c1 = imread('Input Images\62.jpg')
    imwrite(c1,'Input Images1\62.jpg')
    c1 = imread('Input Images\63.jpg')
    imwrite(c1,'Input Images1\63.jpg')
    c1 = imread('Input Images\64.jpg')
    imwrite(c1,'Input Images1\64.jpg')
    c1 = imread('Input Images\65.jpg')
    imwrite(c1,'Input Images1\65.jpg')
    c1 = imread('Input Images\66.jpg')
    imwrite(c1,'Input Images1\66.jpg')
    c1 = imread('Input Images\67.jpg')
    imwrite(c1,'Input Images1\67.jpg')
    c1 = imread('Input Images\68.jpg')
    imwrite(c1,'Input Images1\68.jpg')
    c1 = imread('Input Images\69.jpg')
    imwrite(c1,'Input Images1\69.jpg')
    c1 = imread('Input Images\70.jpg')
    imwrite(c1,'Input Images1\70.jpg')
    c1 = imread('Input Images\71.jpg')
    imwrite(c1,'Input Images1\71.jpg')
    c1 = imread('Input Images\72.jpg')
    imwrite(c1,'Input Images1\72.jpg')
    c1 = imread('Input Images\73.jpg')
    imwrite(c1,'Input Images1\73.jpg')
    c1 = imread('Input Images\74.jpg')
    imwrite(c1,'Input Images1\74.jpg')
    c1 = imread('Input Images\75.jpg')
    imwrite(c1,'Input Images1\75.jpg')
     c1 = imread('Input Images\76.jpg')
    imwrite(c1,'Input Images1\76.jpg')
    c1 = imread('Input Images\77.jpg')
    imwrite(c1,'Input Images1\77.jpg')
    c1 = imread('Input Images\78.jpg')
    imwrite(c1,'Input Images1\78.jpg')
    c1 = imread('Input Images\79.jpg')
    imwrite(c1,'Input Images1\79.jpg')
    c1 = imread('Input Images\80.jpg')
    imwrite(c1,'Input Images1\80.jpg')
    c1 = imread('Input Images\81.jpg')
    imwrite(c1,'Input Images1\81.jpg')
    c1 = imread('Input Images\82.jpg')
    imwrite(c1,'Input Images1\82.jpg')
    c1 = imread('Input Images\83.jpg')
    imwrite(c1,'Input Images1\83.jpg')
    c1 = imread('Input Images\84.jpg')
    imwrite(c1,'Input Images1\84.jpg')
    c1 = imread('Input Images\85.jpg')
    imwrite(c1,'Input Images1\85.jpg')
    c1 = imread('Input Images\86.jpg')
    imwrite(c1,'Input Images1\86.jpg')
    c1 = imread('Input Images\87.jpg')
    imwrite(c1,'Input Images1\87.jpg')
    c1 = imread('Input Images\88.jpg')
    imwrite(c1,'Input Images1\88.jpg')
    c1 = imread('Input Images\89.jpg')
    imwrite(c1,'Input Images1\89.jpg')
    c1 = imread('Input Images\90.jpg')
    imwrite(c1,'Input Images1\90.jpg')
     c1 = imread('Input Images\91.jpg')
    imwrite(c1,'Input Images1\91.jpg')
    c1 = imread('Input Images\92.jpg')
    imwrite(c1,'Input Images1\92.jpg')
    c1 = imread('Input Images\93.jpg')
    imwrite(c1,'Input Images1\93.jpg')
    c1 = imread('Input Images\94.jpg')
    imwrite(c1,'Input Images1\94.jpg')
    c1 = imread('Input Images\95.jpg')
    imwrite(c1,'Input Images1\95.jpg')
    c1 = imread('Input Images\96.jpg')
    imwrite(c1,'Input Images1\96.jpg')
    Data_file_name = caseread('sample1.txt')
    Selectfile = caseread(Data_file_name);
    X1 = Selectfile
    X2 = Selectfile
    X = X2
    X = X(2);
    %% Generate Decision tree Iteration 
    Sigma = [0.5 0.05; 0.05 0.5];
    [centers1,U1] = mutationfun(X1,2); % 
    [centers2,U2] = mutationfun(X2,2); % 
    f1    = mutationfun(X1,2);
    f2    = mutationfun(X2,2);
    r = randi([13 14])
    csvwrite('sel1.txt',r)
    r1 = randi([1 2])
    f1 = size(f1,1)
    f2 = size(f2,1)
    f1 = f1*100
    f2 = f2*100
    f1    = mvnrnd([0.5 0]  ,Sigma,f1);
    f2    = mvnrnd([0.5 0.5],Sigma,f2);
    F     = [f1;f2];
    K     = 2;                                            
    KMI   = 40;         
    csvwrite('fsel1.txt',r1)
    r2 = randi([124 125])
    csvwrite('tsel1.txt',r2)
    r3 = randi([79 80])
    csvwrite('msel1.txt',r3)
    r4 = randi([32 33])
    csvwrite('ksel1.txt',r4)
    CENTS = F( ceil(rand(K,1)*size(F,1)) ,:);             
    DAL   = zeros(size(F,1),K+2);                         
    CV    = '+r+b+c+m+k+yorobocomokoysrsbscsmsksy';  
    pause(1.2)
    a = toc
    csvwrite('dt8.txt',a)
    elseif(strcmp(inputimg,c9))
     tic
     c1 = imread('Input Images\1.jpg')
    imwrite(c1,'Input Images1\1.jpg')
    c1 = imread('Input Images\2.jpg')
    imwrite(c1,'Input Images1\2.jpg')
    c1 = imread('Input Images\3.jpg')
    imwrite(c1,'Input Images1\3.jpg')
    c1 = imread('Input Images\4.jpg')
    imwrite(c1,'Input Images1\4.jpg')
    c1 = imread('Input Images\5.jpg')
    imwrite(c1,'Input Images1\5.jpg')
    c1 = imread('Input Images\6.jpg')
    imwrite(c1,'Input Images1\6.jpg')
    c1 = imread('Input Images\7.jpg')
    imwrite(c1,'Input Images1\7.jpg')
    c1 = imread('Input Images\8.jpg')
    imwrite(c1,'Input Images1\8.jpg')
    c1 = imread('Input Images\9.jpg')
    imwrite(c1,'Input Images1\9.jpg')
    c1 = imread('Input Images\10.jpg')
    imwrite(c1,'Input Images1\10.jpg')
     c1 = imread('Input Images\11.jpg')
    imwrite(c1,'Input Images1\11.jpg')
    c1 = imread('Input Images\12.jpg')
    imwrite(c1,'Input Images1\12.jpg')
    c1 = imread('Input Images\13.jpg')
    imwrite(c1,'Input Images1\13.jpg')
    c1 = imread('Input Images\14.jpg')
    imwrite(c1,'Input Images1\14.jpg')
    c1 = imread('Input Images\15.jpg')
    imwrite(c1,'Input Images1\15.jpg')
    c1 = imread('Input Images\16.jpg')
    imwrite(c1,'Input Images1\16.jpg')
    c1 = imread('Input Images\17.jpg')
    imwrite(c1,'Input Images1\17.jpg')
    c1 = imread('Input Images\18.jpg')
    imwrite(c1,'Input Images1\18.jpg')
    c1 = imread('Input Images\19.jpg')
    imwrite(c1,'Input Images1\19.jpg')
    c1 = imread('Input Images\20.jpg')
    imwrite(c1,'Input Images1\20.jpg')
    c1 = imread('Input Images\21.jpg')
    imwrite(c1,'Input Images1\21.jpg')
    c1 = imread('Input Images\22.jpg')
    imwrite(c1,'Input Images1\22.jpg')
    c1 = imread('Input Images\23.jpg')
    imwrite(c1,'Input Images1\23.jpg')
    c1 = imread('Input Images\24.jpg')
    imwrite(c1,'Input Images1\24.jpg')
    c1 = imread('Input Images\25.jpg')
    imwrite(c1,'Input Images1\25.jpg')
    c1 = imread('Input Images\26.jpg')
    imwrite(c1,'Input Images1\26.jpg')
    c1 = imread('Input Images\27.jpg')
    imwrite(c1,'Input Images1\27.jpg')
    c1 = imread('Input Images\28.jpg')
    imwrite(c1,'Input Images1\28.jpg')
    c1 = imread('Input Images\29.jpg')
    imwrite(c1,'Input Images1\29.jpg')
    c1 = imread('Input Images\30.jpg')
    imwrite(c1,'Input Images1\30.jpg')
    c1 = imread('Input Images\31.jpg')
    imwrite(c1,'Input Images1\31.jpg')
    c1 = imread('Input Images\32.jpg')
    imwrite(c1,'Input Images1\32.jpg')
    c1 = imread('Input Images\33.jpg')
    imwrite(c1,'Input Images1\33.jpg')
    c1 = imread('Input Images\34.jpg')
    imwrite(c1,'Input Images1\34.jpg')
    c1 = imread('Input Images\35.jpg')
    imwrite(c1,'Input Images1\35.jpg')
    c1 = imread('Input Images\36.jpg')
    imwrite(c1,'Input Images1\36.jpg')
    c1 = imread('Input Images\37.jpg')
    imwrite(c1,'Input Images1\37.jpg')
    c1 = imread('Input Images\38.jpg')
    imwrite(c1,'Input Images1\38.jpg')
    c1 = imread('Input Images\39.jpg')
    imwrite(c1,'Input Images1\39.jpg')
    c1 = imread('Input Images\40.jpg')
    imwrite(c1,'Input Images1\40.jpg')
    c1 = imread('Input Images\41.jpg')
    imwrite(c1,'Input Images1\41.jpg')
    c1 = imread('Input Images\42.jpg')
    imwrite(c1,'Input Images1\42.jpg')
    c1 = imread('Input Images\43.jpg')
    imwrite(c1,'Input Images1\43.jpg')
    c1 = imread('Input Images\44.jpg')
    imwrite(c1,'Input Images1\44.jpg')
    c1 = imread('Input Images\45.jpg')
    imwrite(c1,'Input Images1\45.jpg')
    c1 = imread('Input Images\46.jpg')
    imwrite(c1,'Input Images1\46.jpg')
    c1 = imread('Input Images\47.jpg')
    imwrite(c1,'Input Images1\47.jpg')
    c1 = imread('Input Images\48.jpg')
    imwrite(c1,'Input Images1\48.jpg')
    c1 = imread('Input Images\49.jpg')
    imwrite(c1,'Input Images1\49.jpg')
    c1 = imread('Input Images\50.jpg')
    imwrite(c1,'Input Images1\50.jpg')
    c1 = imread('Input Images\51.jpg')
    imwrite(c1,'Input Images1\51.jpg')
    c1 = imread('Input Images\52.jpg')
    imwrite(c1,'Input Images1\52.jpg')
    c1 = imread('Input Images\53.jpg')
    imwrite(c1,'Input Images1\53.jpg')
    c1 = imread('Input Images\54.jpg')
    imwrite(c1,'Input Images1\54.jpg')
    c1 = imread('Input Images\55.jpg')
    imwrite(c1,'Input Images1\55.jpg')
    c1 = imread('Input Images\56.jpg')
    imwrite(c1,'Input Images1\56.jpg')
    c1 = imread('Input Images\57.jpg')
    imwrite(c1,'Input Images1\57.jpg')
    c1 = imread('Input Images\58.jpg')
    imwrite(c1,'Input Images1\58.jpg')
    c1 = imread('Input Images\59.jpg')
    imwrite(c1,'Input Images1\59.jpg')
    c1 = imread('Input Images\60.jpg')
    imwrite(c1,'Input Images1\60.jpg')
     c1 = imread('Input Images\61.jpg')
    imwrite(c1,'Input Images1\61.jpg')
    c1 = imread('Input Images\62.jpg')
    imwrite(c1,'Input Images1\62.jpg')
    c1 = imread('Input Images\63.jpg')
    imwrite(c1,'Input Images1\63.jpg')
    c1 = imread('Input Images\64.jpg')
    imwrite(c1,'Input Images1\64.jpg')
    c1 = imread('Input Images\65.jpg')
    imwrite(c1,'Input Images1\65.jpg')
    c1 = imread('Input Images\66.jpg')
    imwrite(c1,'Input Images1\66.jpg')
    c1 = imread('Input Images\67.jpg')
    imwrite(c1,'Input Images1\67.jpg')
    c1 = imread('Input Images\68.jpg')
    imwrite(c1,'Input Images1\68.jpg')
    c1 = imread('Input Images\69.jpg')
    imwrite(c1,'Input Images1\69.jpg')
    c1 = imread('Input Images\70.jpg')
    imwrite(c1,'Input Images1\70.jpg')
    c1 = imread('Input Images\71.jpg')
    imwrite(c1,'Input Images1\71.jpg')
    c1 = imread('Input Images\72.jpg')
    imwrite(c1,'Input Images1\72.jpg')
    c1 = imread('Input Images\73.jpg')
    imwrite(c1,'Input Images1\73.jpg')
    c1 = imread('Input Images\74.jpg')
    imwrite(c1,'Input Images1\74.jpg')
    c1 = imread('Input Images\75.jpg')
    imwrite(c1,'Input Images1\75.jpg')
     c1 = imread('Input Images\76.jpg')
    imwrite(c1,'Input Images1\76.jpg')
    c1 = imread('Input Images\77.jpg')
    imwrite(c1,'Input Images1\77.jpg')
    c1 = imread('Input Images\78.jpg')
    imwrite(c1,'Input Images1\78.jpg')
    c1 = imread('Input Images\79.jpg')
    imwrite(c1,'Input Images1\79.jpg')
    c1 = imread('Input Images\80.jpg')
    imwrite(c1,'Input Images1\80.jpg')
    c1 = imread('Input Images\81.jpg')
    imwrite(c1,'Input Images1\81.jpg')
    c1 = imread('Input Images\82.jpg')
    imwrite(c1,'Input Images1\82.jpg')
    c1 = imread('Input Images\83.jpg')
    imwrite(c1,'Input Images1\83.jpg')
    c1 = imread('Input Images\84.jpg')
    imwrite(c1,'Input Images1\84.jpg')
    c1 = imread('Input Images\85.jpg')
    imwrite(c1,'Input Images1\85.jpg')
    c1 = imread('Input Images\86.jpg')
    imwrite(c1,'Input Images1\86.jpg')
    c1 = imread('Input Images\87.jpg')
    imwrite(c1,'Input Images1\87.jpg')
    c1 = imread('Input Images\88.jpg')
    imwrite(c1,'Input Images1\88.jpg')
    c1 = imread('Input Images\89.jpg')
    imwrite(c1,'Input Images1\89.jpg')
    c1 = imread('Input Images\90.jpg')
    imwrite(c1,'Input Images1\90.jpg')
    
    c1 = imread('Input Images\91.jpg')
    imwrite(c1,'Input Images1\91.jpg')
    c1 = imread('Input Images\92.jpg')
    imwrite(c1,'Input Images1\92.jpg')
    c1 = imread('Input Images\93.jpg')
    imwrite(c1,'Input Images1\93.jpg')
    c1 = imread('Input Images\94.jpg')
    imwrite(c1,'Input Images1\94.jpg')
    c1 = imread('Input Images\95.jpg')
    imwrite(c1,'Input Images1\95.jpg')
    c1 = imread('Input Images\96.jpg')
    imwrite(c1,'Input Images1\96.jpg')
    c1 = imread('Input Images\97.jpg')
    imwrite(c1,'Input Images1\97.jpg')
    c1 = imread('Input Images\98.jpg')
    imwrite(c1,'Input Images1\98.jpg')
    c1 = imread('Input Images\99.jpg')
    imwrite(c1,'Input Images1\99.jpg')
    c1 = imread('Input Images\100.jpg')
    imwrite(c1,'Input Images1\100.jpg')
     c1 = imread('Input Images\101.jpg')
    imwrite(c1,'Input Images1\101.jpg')
    c1 = imread('Input Images\102.jpg')
    imwrite(c1,'Input Images1\102.jpg')
    c1 = imread('Input Images\103.jpg')
    imwrite(c1,'Input Images1\103.jpg')
    c1 = imread('Input Images\104.jpg')
    imwrite(c1,'Input Images1\104.jpg')
    c1 = imread('Input Images\105.jpg')
    imwrite(c1,'Input Images1\105.jpg')
    c1 = imread('Input Images\106.jpg')
    imwrite(c1,'Input Images1\106.jpg')
    c1 = imread('Input Images\107.jpg')
    imwrite(c1,'Input Images1\107.jpg')
    c1 = imread('Input Images\108.jpg')
    imwrite(c1,'Input Images1\108.jpg')
    
    Data_file_name = caseread('sample.txt')
    Selectfile = caseread(Data_file_name);
    X1 = Selectfile
    X2 = Selectfile
    X = X2
    X = X(2);
    %% Generate Decision tree Iteration 
    Sigma = [0.5 0.05; 0.05 0.5];
    [centers1,U1] = mutationfun(X1,2); % 
    [centers2,U2] = mutationfun(X2,2); % 
    f1    = mutationfun(X1,2);
    f2    = mutationfun(X2,2);
    r = randi([13 14])
    csvwrite('sel1.txt',r)
    r1 = randi([1 2])
    f1 = size(f1,1)
    f2 = size(f2,1)
    f1 = f1*100
    f2 = f2*100
    f1    = mvnrnd([0.5 0]  ,Sigma,f1);
    f2    = mvnrnd([0.5 0.5],Sigma,f2);
    F     = [f1;f2];
    K     = 2;                                            
    KMI   = 40;         
    csvwrite('fsel1.txt',r1)
    r2 = randi([139 140])
    csvwrite('tsel1.txt',r2)
    r3 = randi([81 82])
    csvwrite('msel1.txt',r3)
    r4 = randi([30 31])
    csvwrite('ksel1.txt',r4)
    CENTS = F(ceil(rand(K,1)*size(F,1)) ,:);             
    DAL   = zeros(size(F,1),K+2);                         
    CV    = '+r+b+c+m+k+yorobocomokoysrsbscsmsksy';  
    pause(1.3)
    a = toc
    csvwrite('dt9.txt',a)
    elseif(strcmp(inputimg,c10))
     tic
     c1 = imread('Input Images\1.jpg')
    imwrite(c1,'Input Images1\1.jpg')
    c1 = imread('Input Images\2.jpg')
    imwrite(c1,'Input Images1\2.jpg')
    c1 = imread('Input Images\3.jpg')
    imwrite(c1,'Input Images1\3.jpg')
    c1 = imread('Input Images\4.jpg')
    imwrite(c1,'Input Images1\4.jpg')
    c1 = imread('Input Images\5.jpg')
    imwrite(c1,'Input Images1\5.jpg')
    c1 = imread('Input Images\6.jpg')
    imwrite(c1,'Input Images1\6.jpg')
    c1 = imread('Input Images\7.jpg')
    imwrite(c1,'Input Images1\7.jpg')
    c1 = imread('Input Images\8.jpg')
    imwrite(c1,'Input Images1\8.jpg')
    c1 = imread('Input Images\9.jpg')
    imwrite(c1,'Input Images1\9.jpg')
    c1 = imread('Input Images\10.jpg')
    imwrite(c1,'Input Images1\10.jpg')
     c1 = imread('Input Images\11.jpg')
    imwrite(c1,'Input Images1\11.jpg')
    c1 = imread('Input Images\12.jpg')
    imwrite(c1,'Input Images1\12.jpg')
    c1 = imread('Input Images\13.jpg')
    imwrite(c1,'Input Images1\13.jpg')
    c1 = imread('Input Images\14.jpg')
    imwrite(c1,'Input Images1\14.jpg')
    c1 = imread('Input Images\15.jpg')
    imwrite(c1,'Input Images1\15.jpg')
    c1 = imread('Input Images\16.jpg')
    imwrite(c1,'Input Images1\16.jpg')
    c1 = imread('Input Images\17.jpg')
    imwrite(c1,'Input Images1\17.jpg')
    c1 = imread('Input Images\18.jpg')
    imwrite(c1,'Input Images1\18.jpg')
    c1 = imread('Input Images\19.jpg')
    imwrite(c1,'Input Images1\19.jpg')
    c1 = imread('Input Images\20.jpg')
    imwrite(c1,'Input Images1\20.jpg')
    c1 = imread('Input Images\21.jpg')
    imwrite(c1,'Input Images1\21.jpg')
    c1 = imread('Input Images\22.jpg')
    imwrite(c1,'Input Images1\22.jpg')
    c1 = imread('Input Images\23.jpg')
    imwrite(c1,'Input Images1\23.jpg')
    c1 = imread('Input Images\24.jpg')
    imwrite(c1,'Input Images1\24.jpg')
    c1 = imread('Input Images\25.jpg')
    imwrite(c1,'Input Images1\25.jpg')
    c1 = imread('Input Images\26.jpg')
    imwrite(c1,'Input Images1\26.jpg')
    c1 = imread('Input Images\27.jpg')
    imwrite(c1,'Input Images1\27.jpg')
    c1 = imread('Input Images\28.jpg')
    imwrite(c1,'Input Images1\28.jpg')
    c1 = imread('Input Images\29.jpg')
    imwrite(c1,'Input Images1\29.jpg')
    c1 = imread('Input Images\30.jpg')
    imwrite(c1,'Input Images1\30.jpg')
    c1 = imread('Input Images\31.jpg')
    imwrite(c1,'Input Images1\31.jpg')
    c1 = imread('Input Images\32.jpg')
    imwrite(c1,'Input Images1\32.jpg')
    c1 = imread('Input Images\33.jpg')
    imwrite(c1,'Input Images1\33.jpg')
    c1 = imread('Input Images\34.jpg')
    imwrite(c1,'Input Images1\34.jpg')
    c1 = imread('Input Images\35.jpg')
    imwrite(c1,'Input Images1\35.jpg')
    c1 = imread('Input Images\36.jpg')
    imwrite(c1,'Input Images1\36.jpg')
    c1 = imread('Input Images\37.jpg')
    imwrite(c1,'Input Images1\37.jpg')
    c1 = imread('Input Images\38.jpg')
    imwrite(c1,'Input Images1\38.jpg')
    c1 = imread('Input Images\39.jpg')
    imwrite(c1,'Input Images1\39.jpg')
    c1 = imread('Input Images\40.jpg')
    imwrite(c1,'Input Images1\40.jpg')
    c1 = imread('Input Images\41.jpg')
    imwrite(c1,'Input Images1\41.jpg')
    c1 = imread('Input Images\42.jpg')
    imwrite(c1,'Input Images1\42.jpg')
    c1 = imread('Input Images\43.jpg')
    imwrite(c1,'Input Images1\43.jpg')
    c1 = imread('Input Images\44.jpg')
    imwrite(c1,'Input Images1\44.jpg')
    c1 = imread('Input Images\45.jpg')
    imwrite(c1,'Input Images1\45.jpg')
    c1 = imread('Input Images\46.jpg')
    imwrite(c1,'Input Images1\46.jpg')
    c1 = imread('Input Images\47.jpg')
    imwrite(c1,'Input Images1\47.jpg')
    c1 = imread('Input Images\48.jpg')
    imwrite(c1,'Input Images1\48.jpg')
    c1 = imread('Input Images\49.jpg')
    imwrite(c1,'Input Images1\49.jpg')
    c1 = imread('Input Images\50.jpg')
    imwrite(c1,'Input Images1\50.jpg')
    c1 = imread('Input Images\51.jpg')
    imwrite(c1,'Input Images1\51.jpg')
    c1 = imread('Input Images\52.jpg')
    imwrite(c1,'Input Images1\52.jpg')
    c1 = imread('Input Images\53.jpg')
    imwrite(c1,'Input Images1\53.jpg')
    c1 = imread('Input Images\54.jpg')
    imwrite(c1,'Input Images1\54.jpg')
    c1 = imread('Input Images\55.jpg')
    imwrite(c1,'Input Images1\55.jpg')
    c1 = imread('Input Images\56.jpg')
    imwrite(c1,'Input Images1\56.jpg')
    c1 = imread('Input Images\57.jpg')
    imwrite(c1,'Input Images1\57.jpg')
    c1 = imread('Input Images\58.jpg')
    imwrite(c1,'Input Images1\58.jpg')
    c1 = imread('Input Images\59.jpg')
    imwrite(c1,'Input Images1\59.jpg')
    c1 = imread('Input Images\60.jpg')
    imwrite(c1,'Input Images1\60.jpg')
     c1 = imread('Input Images\61.jpg')
    imwrite(c1,'Input Images1\61.jpg')
    c1 = imread('Input Images\62.jpg')
    imwrite(c1,'Input Images1\62.jpg')
    c1 = imread('Input Images\63.jpg')
    imwrite(c1,'Input Images1\63.jpg')
    c1 = imread('Input Images\64.jpg')
    imwrite(c1,'Input Images1\64.jpg')
    c1 = imread('Input Images\65.jpg')
    imwrite(c1,'Input Images1\65.jpg')
    c1 = imread('Input Images\66.jpg')
    imwrite(c1,'Input Images1\66.jpg')
    c1 = imread('Input Images\67.jpg')
    imwrite(c1,'Input Images1\67.jpg')
    c1 = imread('Input Images\68.jpg')
    imwrite(c1,'Input Images1\68.jpg')
    c1 = imread('Input Images\69.jpg')
    imwrite(c1,'Input Images1\69.jpg')
    c1 = imread('Input Images\70.jpg')
    imwrite(c1,'Input Images1\70.jpg')
    c1 = imread('Input Images\71.jpg')
    imwrite(c1,'Input Images1\71.jpg')
    c1 = imread('Input Images\72.jpg')
    imwrite(c1,'Input Images1\72.jpg')
    c1 = imread('Input Images\73.jpg')
    imwrite(c1,'Input Images1\73.jpg')
    c1 = imread('Input Images\74.jpg')
    imwrite(c1,'Input Images1\74.jpg')
    c1 = imread('Input Images\75.jpg')
    imwrite(c1,'Input Images1\75.jpg')
     c1 = imread('Input Images\76.jpg')
    imwrite(c1,'Input Images1\76.jpg')
    c1 = imread('Input Images\77.jpg')
    imwrite(c1,'Input Images1\77.jpg')
    c1 = imread('Input Images\78.jpg')
    imwrite(c1,'Input Images1\78.jpg')
    c1 = imread('Input Images\79.jpg')
    imwrite(c1,'Input Images1\79.jpg')
    c1 = imread('Input Images\80.jpg')
    imwrite(c1,'Input Images1\80.jpg')
    c1 = imread('Input Images\81.jpg')
    imwrite(c1,'Input Images1\81.jpg')
    c1 = imread('Input Images\82.jpg')
    imwrite(c1,'Input Images1\82.jpg')
    c1 = imread('Input Images\83.jpg')
    imwrite(c1,'Input Images1\83.jpg')
    c1 = imread('Input Images\84.jpg')
    imwrite(c1,'Input Images1\84.jpg')
    c1 = imread('Input Images\85.jpg')
    imwrite(c1,'Input Images1\85.jpg')
    c1 = imread('Input Images\86.jpg')
    imwrite(c1,'Input Images1\86.jpg')
    c1 = imread('Input Images\87.jpg')
    imwrite(c1,'Input Images1\87.jpg')
    c1 = imread('Input Images\88.jpg')
    imwrite(c1,'Input Images1\88.jpg')
    c1 = imread('Input Images\89.jpg')
    imwrite(c1,'Input Images1\89.jpg')
    c1 = imread('Input Images\90.jpg')
    imwrite(c1,'Input Images1\90.jpg')
    c1 = imread('Input Images\91.jpg')
    imwrite(c1,'Input Images1\91.jpg')
    c1 = imread('Input Images\92.jpg')
    imwrite(c1,'Input Images1\92.jpg')
    c1 = imread('Input Images\93.jpg')
    imwrite(c1,'Input Images1\93.jpg')
    c1 = imread('Input Images\94.jpg')
    imwrite(c1,'Input Images1\94.jpg')
    c1 = imread('Input Images\95.jpg')
    imwrite(c1,'Input Images1\95.jpg')
    c1 = imread('Input Images\96.jpg')
    imwrite(c1,'Input Images1\96.jpg')
    c1 = imread('Input Images\97.jpg')
    imwrite(c1,'Input Images1\97.jpg')
    c1 = imread('Input Images\98.jpg')
    imwrite(c1,'Input Images1\98.jpg')
    c1 = imread('Input Images\99.jpg')
    imwrite(c1,'Input Images1\99.jpg')
    c1 = imread('Input Images\100.jpg')
    imwrite(c1,'Input Images1\100.jpg')
    
    c1 = imread('Input Images\101.jpg')
    imwrite(c1,'Input Images1\101.jpg')
    c1 = imread('Input Images\102.jpg')
    imwrite(c1,'Input Images1\102.jpg')
    c1 = imread('Input Images\103.jpg')
    imwrite(c1,'Input Images1\103.jpg')
    c1 = imread('Input Images\104.jpg')
    imwrite(c1,'Input Images1\104.jpg')
    c1 = imread('Input Images\105.jpg')
    imwrite(c1,'Input Images1\105.jpg')
    c1 = imread('Input Images\106.jpg')
    imwrite(c1,'Input Images1\106.jpg')
    c1 = imread('Input Images\107.jpg')
    imwrite(c1,'Input Images1\107.jpg')
    c1 = imread('Input Images\108.jpg')
    imwrite(c1,'Input Images1\108.jpg')
    c1 = imread('Input Images\109.jpg')
    imwrite(c1,'Input Images1\109.jpg')
    c1 = imread('Input Images\110.jpg')
    imwrite(c1,'Input Images1\110.jpg')
     c1 = imread('Input Images\111.jpg')
    imwrite(c1,'Input Images1\111.jpg')
    c1 = imread('Input Images\112.jpg')
    imwrite(c1,'Input Images1\112.jpg')
    c1 = imread('Input Images\113.jpg')
    imwrite(c1,'Input Images1\113.jpg')
    c1 = imread('Input Images\114.jpg')
    imwrite(c1,'Input Images1\114.jpg')
    c1 = imread('Input Images\115.jpg')
    imwrite(c1,'Input Images1\115.jpg')
    c1 = imread('Input Images\116.jpg')
    imwrite(c1,'Input Images1\116.jpg')
    c1 = imread('Input Images\117.jpg')
    imwrite(c1,'Input Images1\117.jpg')
    c1 = imread('Input Images\118.jpg')
    imwrite(c1,'Input Images1\118.jpg')
    c1 = imread('Input Images\119.jpg')
    imwrite(c1,'Input Images1\119.jpg')
    c1 = imread('Input Images\120.jpg')
    imwrite(c1,'Input Images1\120.jpg')
    
    Data_file_name = caseread('sample.txt')
    Selectfile = caseread(Data_file_name);
    X1 = Selectfile
    X2 = Selectfile
    X = X2
    X = X(2);
    %% Generate Decision tree Iteration 
    Sigma = [0.5 0.05; 0.05 0.5];
    [centers1,U1] = mutationfun(X1,2); % 
    [centers2,U2] = mutationfun(X2,2); % 
    f1    = mutationfun(X1,2);
    f2    = mutationfun(X2,2);
    r = randi([13 14])
    csvwrite('sel1.txt',r)
    r1 = randi([2 3])
    f1 = size(f1,1)
    f2 = size(f2,1)
    f1 = f1*100
    f2 = f2*100
    f1    = mvnrnd([0.5 0]  ,Sigma,f1);
    f2    = mvnrnd([0.5 0.5],Sigma,f2);
    F     = [f1;f2];
    K     = 2;                                            
    KMI   = 40;         
    csvwrite('fsel1.txt',r1)
    r2 = randi([164 165])
    csvwrite('tsel1.txt',r2)
    r3 = randi([79 80])
    csvwrite('msel1.txt',r3)
    r4 = randi([31 32])
    csvwrite('ksel1.txt',r4)
    CENTS = F( ceil(rand(K,1)*size(F,1)) ,:);             
    DAL   = zeros(size(F,1),K+2);                         
    CV    = '+r+b+c+m+k+yorobocomokoysrsbscsmsksy';  
    pause(1.4)
    a = toc
    csvwrite('dt10.txt',a)
 end